name: Lighthouse Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
     - name: Audit URLs using Lighthouse
       uses: justinribeiro/lighthouse-action@master
       with:
          url: https://webshop-agil-testautomatiserare.netlify.app
          wptConnectionSpeed: threegfast
