name: Lighthouse Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
     - name: Audit URLs using Lighthouse
       uses: treosh/lighthouse-ci-action@v10
       with:
        runs: 3
        urls: |
          https://webshop-agil-testautomatiserare.netlify.app
          
     - name: Lighthouse Report
       uses: manrueda/lighthouse-report-action@v1.0.1
       if: always()
       with:
        reports: '.lighthouseci'
        github-token: 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
